name: unit-test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '**'
jobs:
  unit-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      WORKDIR: .
    steps:
      # Bring code
      - name: checkout
        uses: actions/checkout@v3

      # Setup Node
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      # Install Yarn
      - name: Install Yarn
        run: npm install yarn

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Run unit tests
      - name: Run unit tests
        run: yarn test:coverage

      # Add PR comment based on the result
      - name: Add PR comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
